name: Acquia Build and Deploy Prod

on:
  push:
    branches:
      - main

env:
  GIT_COMMIT_MESSAGE: 'Github Actions Build'

jobs:
  build-theme:
    uses: AtenDesignGroup/aten-actions/.github/workflows/build-theme.yml@main
    with:
      theme-path: ${{ vars.THEME_PATH }}
      build-command: publish
  deploy:
    runs-on: ubuntu-latest
    needs: [build-theme]

    steps:
      - name: Setup Git and Checkout Repo
        uses: AtenDesignGroup/aten-actions/.github/actions/setup-git@main
        with:
          git-remote-url: ${{ vars.ACQUIA_GIT_REMOTE }}

      - name: Setup Remote SSH
        uses: AtenDesignGroup/aten-actions/.github/actions/setup-remote-ssh@main
        with:
          ssh-private-key: ${{ secrets.ACQUIA_SSH_PRIVATE_KEY }}

      - name: Pre Deploy - Composer Install
        uses: AtenDesignGroup/aten-actions/.github/actions/pre-deploy-composer-install@main

      - name: Pre Deploy - Download Theme Artifact
        uses: actions/download-artifact@v4
        with:
          name: theme-artifact
          path: ${{ vars.THEME_PATH }}

      - name: Get tag name
        id: tag
        run: |
          NOW=$(date +'%Y-%m-%dT%H-%M-%S')
          echo "TAG_NAME=v$NOW" >> $GITHUB_OUTPUT

      - name: Test using TAG_NAME in subsequent steps
        id: test_tag_name
        run: |
          echo "TAG_NAME value is: ${{ steps.tag.outputs.TAG_NAME }}"

      - name: Deploy - Git Push to Remote
        uses: AtenDesignGroup/aten-actions/.github/actions/deploy-git-push@git-tag-release
        with:
          git-push-branch: main
          git-commit-message: ${{ env.GIT_COMMIT_MESSAGE }}
          git-tag-release: true
          git-push-flags: '--tag --force'
          git-tag-name: ${{ steps.tag.outputs.TAG_NAME }}

      - name: Post Deploy - Notify Slack
        if: always()
        uses: AtenDesignGroup/aten-actions/.github/actions/post-deploy-notify-slack@main
        with:
          slack-channel-id: ${{ vars.SLACK_CHANNEL }}
          slack-message: "@${{ github.actor }} is pushing code today and it was a ${{ job.status }}!\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nUsing Workflow: ${{ github.workflow }}\nPantheon: https://${{ env.PANTHEON_MULTIDEV }}-${{ vars.PANTHEON_SITE }}.pantheonsite.io"
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
